### ISSUE TITLE
Positions Not Supported

### ISSUE THREAD

**Issue by Ayman97** [stevecochrane/tailwindcss-logical#10]

**Comment by stevecochrane** [comment]
Hi @Ayman97,

I assume you're looking for logical equivalents for the `top` / `right` / `bottom` / `left` properties, like these? https://tailwindcss.com/docs/top-right-bottom-left

You can position elements the same way, but logically, with the Flow-relative Offset utilities. I've listed the utilities that are supported in the README here: https://github.com/stevecochrane/tailwindcss-logical#flow-relative-offsets

You're helping me to notice things that need improvement in the documentation, so thanks for the feedback. I'm going to go ahead and close this issue since I think that should solve it, but feel free to reopen this if this isn't what you were looking for.
