### ISSUE TITLE
Logical Properties cheatsheet

### ISSUE THREAD

**Issue by vltansky** [stevecochrane/tailwindcss-logical#26]
This could be useful (maybe formatted another way) in the readme for those who start using 
https://gist.github.com/vltansky/df11bf8991c10a23694ae8f3620bb658

**Comment by stevecochrane** [comment]
Hi @vltansky, I like this idea. Currently I'm getting ready for the upcoming Tailwind v3 release, but I want to revisit this afterward, possibly either including it in the readme like you mentioned or maybe adding a link to your project from there. I'll keep this issue open for now. Thank you for the suggestion!

**Comment by stevecochrane** [comment]
Hi again @vltansky, sorry it's taken so long for me to get back to you. I've thought about this a bit more and I don't think I should include the cheatsheet in full in the readme, since the readme is already very long. But I could add a sentence that links to your cheatsheet so others could use it as a resource. Does that sound good?

Also, since your original message I've added support for the following in v3.0.0:
- `border-block-width` (new classes: `border-lb-*`, corresponds to `border-y-*`)
- `border-inline-width` (new classes: `border-li-*`, corresponds to `border-x-*`)
- `border-block-color` (same `border-lb-*` prefix as above, but for color values)
- `border-inline-color` (same `border-li-*` prefix as above, but for color values)

**Comment by stevecochrane** [comment]
Marking as closed since it's been a while since I've heard anything about this.
